# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: "ubuntu-18.04"
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - uses: ros-tooling/setup-ros@v0.1
      with:
        required-ros-distributions: melodic
    - uses: ros-tooling/action-ros-ci@v0.1
      with:
        package-name: catkin_test_pkg
        target-ros1-distro: melodic
        vcs-repo-file-url: ""
